// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjIaLuPMEixmT6xNgnAiyNbMw7YzP5NBs',
    appId: '1:224642949303:web:cb0853c4dc366aad99ed32',
    messagingSenderId: '224642949303',
    projectId: 'hrplatformportal',
    authDomain: 'hrplatformportal.firebaseapp.com',
    databaseURL: 'https://hrplatformportal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hrplatformportal.appspot.com',
    measurementId: 'G-K64NMNC2P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYwHAHQrJK8VT_oB8Ao4ScS0nWGt6diGA',
    appId: '1:224642949303:android:213a55d9ba9dd6f999ed32',
    messagingSenderId: '224642949303',
    projectId: 'hrplatformportal',
    databaseURL: 'https://hrplatformportal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hrplatformportal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX247SylCphCsXld0UoJu6huMBm2MrVpU',
    appId: '1:224642949303:ios:75ac6cf1184df43d99ed32',
    messagingSenderId: '224642949303',
    projectId: 'hrplatformportal',
    databaseURL: 'https://hrplatformportal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hrplatformportal.appspot.com',
    iosClientId: '224642949303-j936dvuqtsdqnhgkipedg5cu576gen3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX247SylCphCsXld0UoJu6huMBm2MrVpU',
    appId: '1:224642949303:ios:75ac6cf1184df43d99ed32',
    messagingSenderId: '224642949303',
    projectId: 'hrplatformportal',
    databaseURL: 'https://hrplatformportal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hrplatformportal.appspot.com',
    iosClientId: '224642949303-j936dvuqtsdqnhgkipedg5cu576gen3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjIaLuPMEixmT6xNgnAiyNbMw7YzP5NBs',
    appId: '1:224642949303:web:155be69797ba05f599ed32',
    messagingSenderId: '224642949303',
    projectId: 'hrplatformportal',
    authDomain: 'hrplatformportal.firebaseapp.com',
    databaseURL: 'https://hrplatformportal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hrplatformportal.appspot.com',
    measurementId: 'G-6BC4W0T47J',
  );

}